import sys
import os 
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from Rosalind_functions import *
from structures import *

def main():
    seq1 = '''GCGGTCGAATTGCGGGAGGGATAGCCCGATG
    AAAGGACAATTTTTGGAGGCACGGTTATACGATCGCATCCT
    ATTCCGTAGGATGTGCCGTGCTTTCTGTGTTTGAGTGAACC
    CAAGTGGGGGCGAGGGGTACGGCTAACCGGTTTAAACTTTC
    CATATGGCCGGCAGCTCAACGAAGGGCTTCGACCTGAATAG
    TAGGACATTTGTCGAGTCACGATCGCTCCATCCTGTACTCT
    GTGACGATCAGATATGCGCGTCCAGTGCAGATAGTCCACTG
    ACAGACGGAAAATCGCCTGGAGACGCAATTTCACAGCGTCCC
    CTCTGAAGCGTTGATGCGTAGCGGAAGCTTGACTCACGAAAA
    TGTTAGTCCATTGGGCTCTACTAGGAACAAATGCCCCGCAACT
    TAGTGAGCCTTTATACCGGTCGCTGTTGTATTTGGTTCGCTGC
    CGTTGACTATATAATCGCGCACGATATCGCTATATTCCTCTAAC
    CTAGTCGCAATTCAATGGTAGTCGCTCCACAAAGCCCGGGCCCCG
    TGTGCTAAAGATACCTGCGATCAAAGCGAAAGCAGTATACAGCTC
    CGCTTAGGATCGCGTGGCCGATATAAATGGGATATTAGTTCTTCCC
    TTTAGAGCTTGAAGAGAATAATATAATCACAATTACGTCACCGAGG
    CGGCTCTGTGTTATCGCCTCAAGGTATCCTAGTGGGTCGGCAGGGG
    TGTTTGGAACACACGTTCCGAGTTGTAGAATCCGGCGCCGACTTAAG
    CATGGTCTGTATTGTATACACCGCGTTCGCCTGCGATGTGCCGTGAA
    AACGTCTCGGTGGTCTCGCGGTGCCGTACCCATCGGGCTGATTCAAT
    CGTATGGGAACTTAGTGCGGAAATCAGCGAACCATAGAATGGTGGTGCC'''
    seq2 = '''GGCTTGGTACTTTGTGAGAGATGCCCTCTTCGCTGGACAT
    CCCTTGGTTGGTGCGGTAAATACTCGAATCGTCTTACCTAGGATGGGCGA
    AGGTTGATGCCATCGGCTTAACGCATATGGCGAATGGGGCACTGCCTCGGT
    AGTCTCGATTTACAATGTGGCCTTGATGGCAAAAAATGGCCCCGAGCACTA
    TGAGTGAACGTTGGCAGTGGCACAAGGTGACTAAGCTAGACTGTCTGAGGC
    TCCGATCCCCGTCGCCCGTAGATAAAGACCGTTGCCCAATGAATAATCTTTA
    TGAGGGCATACTTAAGAAAGTCTCTTCAGTCGGTTTCAGGAATTTCGGAAGC
    TTGGGTGCCGAATTAGTTCGGGCAGTTGGCCCACGCCACCTCGCTTAACCAA
    CAACCTTACAAGGCTTTATATTGGTTACCGTTACACTTGGGAGCACACGGTGG
    ACTGTCTCTTAGAGTACGAGATTGCTAAACCCTGCAAATCAACTACATAAGTA
    ATGATAGACGCTTCTTTGACATCTGGGCCCGTGTAATAGATATAGTTCACAGCA
    ACTCAACCTCTGTATAGAGATCCCCCTAGATGCTAGGTTCCGTCATCAATGGGTT
    AGAGGTTGGCCTGTATGGGGTCGATGGGCACCGATAGAACCAACAGAGAGGTGCT
    GGGCCGGATCGGTGGGTGGGCCGCAAGTTGGCATCGTGCGTCAGCTGTGTTTTTT
    GACACACATCATACAGGATTTATCATCCGTACCGGGGTAGTCCGGGGGTACCATTG
    AATGCCTATGGTGCCTTTTGGAGGCGCCGTAAAAACGTGACGATGGTTTATCCGTA
    CTATAGCCATGAGGCAGGCGCTAACAGCGCGGCAGCCAAGTACGGCCGGGCGCAAA
    ACATAGTATACGGAGATC'''

    print(hamming(seq1,seq2))


if __name__ == '__main__':
    main()